# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.4
loader_version=0.16.4
kotlin_loader_version=1.13.0+kotlin.2.1.0
fabric_version=0.113.0+1.21.4

# Dependencies
# check this on https://modmuss50.me/fabric.html
exposed_version=0.57.0
postgresql_version=42.7.4

# Mod Properties
mod_version=0.0.5
maven_group=sh.bims
archives_base_name=player-persistence
